### ISSUE TITLE
Security Sweep

### ISSUE THREAD

**Issue by import-pandas-as-numpy** [vipyrsec/dragonfly-client-rs#46]
- [x] Sanity check client cannot operate on endpoints with bad/revoked creds. (I did this through CURL but didn't check revoked.) 
- [x] Check directory traversal from a passed in package archive. 
- [ ] Check decompression bomb (zip/gzip) from a passed in package archive. 
- [x] Quick check to make sure we're not missing anything glaring CVE wise on stdlib or our deps. CVE's tentatively look good (last one was in 2022 against base Rust-lang) 

I'll review this for anything else that doesn't pass a simple smell test, but hanging on the Rustaceans to give me the warm fuzzies.

**Comment by Robin5605** [comment]
https://github.com/vipyrsec/dragonfly-client-rs/security/dependabot/1 has been fixed in #54
