### ISSUE TITLE
Don't hold all downloaded distributions in memory

### ISSUE THREAD

**Issue by Robin5605** [vipyrsec/dragonfly-client-rs#67]
While we have a limit on the size of *each* distribution, we can still easily OOM our clients if a package with many distributions is being scanned. Instead, we should sequentually fetch each distribution, and scan it, then deallocate the memory needed to store that distribution.

**Comment by jonathan-d-zhang** [comment]
We can stream responses directly into files and avoid sequential fetching.

**Comment by Robin5605** [comment]
> We can stream responses directly into files and avoid sequential fetching.

Do you mean streaming it into the filesystem, as opposed to some sort of in-memory buffer? Is writing potentially malicious software to disk safe? Is it also good practice (i.e is it recommended for containerized applications to write to filesystem?) I've heard that Docker containers are supposed to be immutable (not sure if this applies to an application writing to disk itself, though)
